version: '3.8'
services:
  # NestJS App Service
  app:
    build: .
    ports:
      - '${PORT}:${PORT}' # Use variable for port mapping
    depends_on:
      - db
    env_file:
      - .env # Load environment variables from .env file

  # PostgreSQL Database Service
  db:
    image: postgres:13
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}' # Use variable for port mapping
    env_file:
      - .env # Load environment variables from .env file
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: